# 1 工作流名称
name: CI

# 2 工作流执行名称
run-name: ${{ github.actor }} is update repo, start building...

# 3 控制工作流程何时运行
on:
  # 在推送或拉取请求事件上触发工作流程，但仅限于“master”分支
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

  # 允许您从“操作”选项卡手动运行此工作流程
  workflow_dispatch:

# 4 设置权限（文件是可以被读写修改的）
permissions:
  contents: write

# 工作流程运行由一个或多个可以顺序或并行运行的作业组成
jobs:
  # 该工作流程包含一个名为 "build"
  build:
    # 执行平台
    runs-on: ubuntu-latest

    # 步骤表示将作为作业的一部分执行的一系列任务
    steps:
      # 将代码仓库的内容拉取（或称为检出）到工作目录中，以便在下面的工作流程中使用
      - uses: actions/checkout@v3

      # 安装 node 环境，并设置版本为 18
      - name: Setup Node.js (设置 node 版本)
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 安装依赖
      - name: Install dependencies (安装依赖)
        run: npm install

      # 构建项目
      - name: Build (构建)
        run: npm run docs:build

      # 上传构建产物（actions/upload-artifact@v3 会上传工作流程中的文件，允许您在作业之间共享数据并在工作流程完成后存储数据）
      - name: Upload build artifacts (上传构建产物)
        uses: actions/upload-pages-artifact@v2
        with:
          path: './dist'

      # 9 部署 GitHub Pages
      # - name: Deploy to GitHub Pages(部署到 GitHub Pages)
      #   uses: actions/deploy-pages@v2
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
